# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 244c49d45701b74e7d04330542ca2a7e3a55f79b5f53da6ea11d1d5efd0bce11883d7e7c27cb8785b46eaf27eb22e2c6a8bac8f5551802db0d38278a2ef1fa69

test:
  secret_key_base: 3012a48c364c13a7cd4124144317c7f180cdcb40e2db5e94605cfea7a725b7d3e333dcdd4c038af741e42ba91143813a8d7558d13d32749a96dc5b55cad26c76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
